<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="Kivanc1Hp" failures="1" tests="2" name="Default test(failed)" time="0.052" errors="0" timestamp="2020-04-26T17:45:11 EET">
  <testcase classname="demo.TestNGRetryFailedDemo" name="test2" time="0.008"/>
  <testcase classname="demo.TestNGRetryFailedDemo" name="test3" time="0.006">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:87)
at org.junit.Assert.assertTrue(Assert.java:42)
at org.junit.Assert.assertTrue(Assert.java:53)
at demo.TestNGRetryFailedDemo.test3(TestNGRetryFailedDemo.java:24)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1378)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- test3 -->
  <testcase classname="demo.TestNGRetryFailedDemo" name="test1" time="0.0">
    <ignored/>
  </testcase> <!-- test1 -->
</testsuite> <!-- Default test(failed) -->
